export type Unit = "円" | "千円" | "百万円";
export type Granularity = "medium" | "high";
export type ScaleMode = "actual" | "normalized";
export type ViewMode = "single" | "companies" | "timeline";
export type FinancialRecord = { id:string; company:string; year:string; unit:Unit; cash:number; receivables:number; inventory:number; otherCurrentAssets:number; tangibleAssets:number; intangibleAssets:number; otherFixedAssets:number; currentAssets:number; fixedAssets:number; payables:number; interestDebt:number; otherCurrentLiabilities:number; otherFixedLiabilities:number; currentLiabilities:number; fixedLiabilities:number; equity:number; sales:number; costOfSales:number; sga:number; operatingProfit:number };
export const sample=(id:string=crypto.randomUUID()):FinancialRecord=>({id,company:"サンプル株式会社",year:"2026",unit:"百万円",cash:210,receivables:190,inventory:120,otherCurrentAssets:80,tangibleAssets:260,intangibleAssets:0,otherFixedAssets:140,currentAssets:600,fixedAssets:400,payables:170,interestDebt:0,otherCurrentLiabilities:130,otherFixedLiabilities:0,currentLiabilities:300,fixedLiabilities:200,equity:500,sales:1000,costOfSales:600,sga:300,operatingProfit:100});
export const factor=(u:Unit)=>u==="円"?1:u==="千円"?1_000:1_000_000;
export const fmt=(n:number)=>Math.round(Math.abs(n)).toLocaleString("ja-JP");
export const parseAmount=(s:string)=>{const c=s.replace(/[\s,，]/g,"");return c===""?0:Number(c)};
export function deriveRecord(r:FinancialRecord):FinancialRecord{return{...r,otherCurrentAssets:r.currentAssets-r.cash-r.receivables-r.inventory,otherFixedAssets:r.fixedAssets-r.tangibleAssets,intangibleAssets:0,interestDebt:0,otherCurrentLiabilities:r.currentLiabilities-r.payables,otherFixedLiabilities:0}}
export function aggregate(r:FinancialRecord,_g:Granularity){return{currentAssets:r.currentAssets,fixedAssets:r.fixedAssets,currentLiabilities:r.currentLiabilities,fixedLiabilities:r.fixedLiabilities}}
export function validate(r:FinancialRecord,g:Granularity){const d=deriveRecord(r),a=aggregate(d,g),assets=a.currentAssets+a.fixedAssets,financing=a.currentLiabilities+a.fixedLiabilities+d.equity,plExpected=d.costOfSales+d.sga+d.operatingProfit,warnings:string[]=[];if(Math.abs(assets-financing)>Math.max(1,Math.abs(assets)*.001))warnings.push(`BS不一致：資産合計 ${fmt(assets)}／負債・純資産 ${fmt(financing)}（差額 ${fmt(assets-financing)}）`);if(Math.abs(d.sales-plExpected)>Math.max(1,Math.abs(d.sales)*.001))warnings.push(`PL不一致：売上高 ${fmt(d.sales)}／費用・利益 ${fmt(plExpected)}（差額 ${fmt(d.sales-plExpected)}）`);if([d.otherCurrentAssets,d.otherFixedAssets,d.otherCurrentLiabilities].some(v=>v<0))warnings.push("内訳が合計を超えています。「その他」の自動計算値を確認してください。");if([a.currentAssets,a.fixedAssets,a.currentLiabilities,a.fixedLiabilities,d.sales,d.costOfSales,d.sga].some(v=>v<0))warnings.push("通常は正値となる項目に負の値があります。入力を確認してください。");if(assets<=0)warnings.push("総資産が0以下のため、BSを比例表示できません。");if(d.sales<=0)warnings.push("売上高が0以下のため、PLを比例表示できません。");return{assets,financing,plExpected,warnings}}
